language: java
sudo: false
dist: trusty

notifications:
    email: false

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- find . -name "*.sh" -exec chmod u+x {} \;
- echo "------------------ egg_Basic_Trivial"
- cd egg_Basic_Trivial
- ./compile.sh
- ./run.sh
- echo "------------------ egg_Basic_Dependency"
- cd ../egg_Basic_Dependency
# list commands don't work for some reason 
- ./compile.sh
- ./run_UserDao.sh
- ./run_UserService.sh
- echo "------------------ egg_Open_Module"
- cd ../egg_Open_Module
# list commands don't work for some reason 
- ./compile.sh
- ./run_UserDao.sh
- ./run_UserService.sh
- echo "------------------ egg_Services"
- cd ../egg_Services
# list commands don't work for some reason 
- ./compile.sh
- ./run_Dao.sh
- echo "------------------ egg_Transitive_Export"
- cd ../egg_Transitive_Export
# list commands don't work for some reason 
- ./compile.sh
- ./run_UserDao.sh
- ./run_UserService.sh

- cd ..

