language: java
sudo: false
dist: trusty

notifications:
    email: false

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- find . -name "*.sh" -exec chmod u+x {} \;
- echo "------------------ egg_Basic_Dependency"
- cd egg_Basic_Dependency
- ./compile.sh
- ./run_UserDao.sh
- ./run_UserService.sh

